---
path_to_remove: /cm/local/apps/cuda/libs/current/pynvml
data_file: /gpfs/workspace/users/rezaem/repos/Argenomic-data/data/my_runs_input/guacamol_initial_rediscovery_ref_3.smi
batch_size: 40
initial_size: 100
workers: 1
threads: 2
generations: 75
archive:
  name: ref_3
  jobname: ref3_no_penalty
  size: 150
  accuracy: 25000
descriptor:
  properties:
  - Descriptors.ExactMolWt
  ranges:
  - - 225
    - 555
spec_params:
  rocs_type: shape_and_color
  max_confs: 75
  max_centers: 3
  force_flip: true
  enum_nitrogen: true
fitness:
  target: /gpfs/workspace/users/rezaem/repos/Argenomic-data/data/my_runs_input/fastrocs_Ref_3.sdf
  type: ROCS_3D
  thresholds:
  - 0.9
  - 0.7
  - 0.9
  penalty_weights:
  - 1.0
  - 1.15
  - 1.1
  segment_smis:
  - CC(=O)N1CC[C@H](C1)O
  - c1ccc(cc1)CNC=O
  - c1ccc(cc1)c2cnco2
arbiter:
  rules:
  - Glaxo
